apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flipper-front
      app.kubernetes.io/part-of: flipper
    includeSelectors: true
    includeTemplates: true

images:
  - name: ghcr.io/fouuuadi/flipper-front
