server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index playfield.html;

    location = / {
        try_files /playfield.html =404;
    }

    location = /backglass {
        try_files /backglass.html =404;
    }

    location = /dmd {
        try_files /dmd.html =404;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
