apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flipper-prod

resources:
  - ../../base

images:
  - name: ghcr.io/fouuuadi/flipper-front
    newTag: main-latest

patches:
  - target:
      kind: Deployment
      name: flipper-front
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: flipper-front
      spec:
        replicas: 3
  - target:
      kind: Ingress
      name: flipper-front
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: flipper-front
      spec:
        rules:
          - host: front.prod.local
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: flipper-front
                      port:
                        number: 80
