name: Update Flipper Center (Front)

on:
  push:
    branches:
      - main

jobs:
  update-center:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Flipper Center
        uses: actions/checkout@v4
        with:
          repository: fouuuadi/Flipper_Center
          token: ${{ secrets.CENTER_TOKEN }}
          submodules: true

      - name: Update front submodule
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git submodule update --remote front

          git add front
          git commit -m "Auto update front from ${GITHUB_REPOSITORY}@${GITHUB_SHA}" || echo "No changes"

          git pull --rebase
          git push
